### ISSUE TITLE
Using float16 in WebGL2?

### ISSUE THREAD

**Issue by apbodnar** [petamoriken/float16#105]
Hi. Thanks for making this library.  I have a WebGL2 project that requires potentially thousands of floating point texture reads per draw call.  Cache and bandwidth performance could be improved by using a fp16 texture instead of fp32, but trying to naively use float16.Float16Array as a replacement for Float32Array causes the error  `WebGL: INVALID_OPERATION: texImage2D: no bound PIXEL_UNPACK_BUFFER` in chrome.
My original code is: 
`gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGB32F, res[0], res[1], 0, gl.RGB, gl.FLOAT, new Float32Array(bvhBuffer));`
My new/broken code is:
`gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGB16F, res[0], res[1], 0, gl.RGB, gl.HALF_FLOAT, new float16.Float16Array(bvhBuffer));`

Any guidance would be appreciated.

**Comment by petamoriken** [comment]
`Float16Array` extends `Uint16Array` but `new Float16Array()` returns `Proxy` object that wraps `Float16Array` to handle to get and set indexed properties. Maybe you should apply `Uint16Array` to `WebGL2RenderingContext#texImage2D` instead of `Float16Array`.

Please try:

```js
gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGB16F, res[0], res[1], 0, gl.RGB, gl.HALF_FLOAT, new Uint16Array(bvhBuffer));

// or, when you want to apply Float16Array to calculate the texture in browser
gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGB16F, res[0], res[1], 0, gl.RGB, gl.HALF_FLOAT, new Uint16Array(float16array.buffer));
```

Reference
[WebGL2 Spec 3.7.6 Texture objects](https://www.khronos.org/registry/webgl/specs/latest/2.0/#3.7.6)

**Comment by apbodnar** [comment]
This first option won't work since it'll be casting (presumably) double precision plain js number values to uint16 values, which won't meaningfully reinterpret_cast to the correct fp16 values. 


Thanks for the response.  Using the second option causes a rather amusing crash along with a complete freeze of my display driver: `[.WebGL-0000028BB5EA5AC0] GL_INVALID_OPERATION: Error: 0x00000502, in ../../third_party/angle/src/libANGLE/renderer/d3d/d3d11/Renderer11.cpp, mapResource:3937. Internal D3D11 error: HRESULT: 0x887A0005: Failed to map D3D11 resource.`

Perhaps the WbGL impl isn't interpreting the uin16 bytes as fp16 correctly.

**Comment by petamoriken** [comment]
`bvhBuffer` seems to be data to be read by `Float32Array`.

```js
const float32array = new Float32Array(bvhBuffer);

// cast all indexed properties: f32 to f16
const float16array = new float16.Float16Array.from(float32array);

// apply
gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGB16F, res[0], res[1], 0, gl.RGB, gl.HALF_FLOAT, new Uint16Array(float16array.buffer));
```

**Comment by petamoriken** [comment]
Or [ANGLE](https://chromium.googlesource.com/angle/angle) bugs?

**Comment by apbodnar** [comment]
I haven't been able to get it to work, but I think I'll be able to get away with sending the buffer explicitly as Uint16 and unpacking them in the shader via `unpackHalf2x16`
