### ISSUE TITLE
conversions to float16 are incorrect for very small numbers

### ISSUE THREAD

**Issue by bakkot** [petamoriken/float16#952]
I've been looking into [tests](https://github.com/tc39/test262/issues/3828) now that the proposal is [stage 3](https://github.com/tc39/proposal-float16array/pull/8), and in the process I noticed there's at least one bug in how this library handles rounding of very small values.

Specifically:

The smallest float16 value (call it F16_MIN) is `5.9604644775390625e-8`.

Half of that is `2.98023223876953125e-8`, which is precisely representable as a double, i.e. a JS number.

The next precisely representable double above F16_MIN/2  is `2.980232238769531911744490042422139897126953655970282852649688720703125e-8`. Call that TEST.

TEST should round to F16_MIN: TEST is closer to F16_MIN than to 0. (`F16_MIN - TEST < TEST`)

But `console.log(f16round(2.980232238769531911744490042422139897126953655970282852649688720703125e-8))` gives 0. Per above, that's wrong.

**Comment by petamoriken** [comment]
My bad. I noticed that it apparently rounds the numbers in *truncation* mode. I'll fix it to be in *roundTiesToEven* mode as specified.
